require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
    NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/fixtures/*.rb'

Lint/DuplicateMethods:
  Exclude:
    - 'spec/fixtures/*.rb'

RSpec/FilePath:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/**/**.rb'

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/AbcSize:
  Max: 36

Naming/AccessorMethodName:
  Exclude:
    - '**/**/dsl.rb'
