require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/fixtures/*.rb'

Lint/DuplicateMethods:
  Exclude:
    - 'spec/fixtures/*.rb'

RSpec/FilePath:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/**/**.rb'

# TODO: Fix these...
Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'lib/**/**.rb'

Style/ConditionalAssignment:
  Exclude:
    - 'lib/**/**.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'lib/**/**.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'lib/**/**.rb'

Metrics:
  Exclude:
    - 'lib/**/**.rb'

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'lib/**/**.rb'

Naming/PredicateName:
  Exclude:
    - 'lib/**/**.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'lib/**/**.rb'

Style/CaseLikeIf:
  Exclude:
    - 'lib/fast_jsonapi/object_serializer.rb'

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/fast_jsonapi/serialization_core.rb'
    - 'lib/fast_jsonapi/relationship.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'lib/fast_jsonapi/relationship.rb'

Style/DocumentDynamicEvalDefinition:
  Exclude:
    - 'lib/extensions/has_one.rb'
